apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumemnt
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumeclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volumemnt
provisioner: docker.io/hostpath
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate