# apiVersion: v1
# kind: Pod
# metadata:
#   name: dob-volumes-pod
# spec:
#   volumes:
#     - name: volumemnt
#       persistentVolumeClaim:
#         claimName: volumeclaim
#   containers:
#     - name: alpine
#       image: alpine:v1
#       imagePullPolicy: Never
#       command: ["/bin/sh", "-c"]
#       args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
#       volumeMounts:
#         - name: volumemnt
#           mountPath: /opt

# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: dob-jenkins-pod
# spec:
#   volumes:
#     - name: volumemnt
#       persistentVolumeClaim:
#         claimName: volumeclaim
#   containers:
#     - name: jenkins
#       image: densell321/jenkins:firsttry
#       ports:
#         - containerPort: 8080
#       volumeMounts:
#         - name: volumemnt
#           mountPath: /usr/bin

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: volumemnt
          persistentVolumeClaim:
            claimName: volumeclaim
      containers:
        - name: jenkins
          image: densell321/jenkins:firsttry
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: volumemnt
              mountPath: /usr/bin